In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F

import gym
from IPython.display import display

In [3]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[2022-01-06 14:09:44,145] Making new env: CartPole-v0
/usr/local/lib/python3.9/site-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
2022-01-06 14:09:44.620 Python[16292:23076749] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/2v/0tr3wk2s1tn4fntw0fbqt3fh0000gn/T/org.python.python.savedState


[0.01440763 0.00969192 0.00368159 0.02679372]
[ 0.01460147 -0.18548264  0.00421746  0.32063595]
[0.01089182 0.009579   0.01063018 0.02928603]
[ 0.0110834   0.20454691  0.0112159  -0.2600241 ]
[0.01517434 0.00926665 0.00601542 0.03617526]
[ 0.01535967  0.20430183  0.00673892 -0.25460368]
[ 0.01944571  0.39932691  0.00164685 -0.54515344]
[ 0.02743224  0.59442568 -0.00925622 -0.83731703]
[ 0.03932076  0.78967282 -0.02600256 -1.13289648]
[ 0.05511421  0.9851253  -0.04866049 -1.43361997]
[ 0.07481672  1.1808126  -0.07733289 -1.74110402]
[ 0.09843297  1.37672516 -0.11215497 -2.05680778]
[ 0.12596747  1.18291393 -0.15329112 -1.80082193]
[ 0.14962575  0.98980246 -0.18930756 -1.55944269]
Episode finished after 14 timesteps
[ 0.03032386 -0.01591681 -0.00021245 -0.02142103]
[ 0.03000552 -0.21103571 -0.00064087  0.27119486]
[ 0.02578481 -0.40614851  0.00478302  0.56367558]
[ 0.01766184 -0.60133725  0.01605654  0.85786154]
[ 0.00563509 -0.79667422  0.03321377  1.15554965]
[-0.01029839 -0.99221312  

[-0.02135816  0.14999218 -0.06432355 -0.38529952]
[-0.01835832 -0.04416043 -0.07202954 -0.11357096]
[-0.01924153  0.15191575 -0.07430096 -0.42808097]
[-0.01620321 -0.04207959 -0.08286258 -0.15971522]
[-0.0170448   0.15412489 -0.08605689 -0.47734586]
[-0.01396231 -0.0396833  -0.0956038  -0.21297888]
[-0.01475597  0.15666626 -0.09986338 -0.53422299]
[-0.01162265 -0.03691997 -0.11054784 -0.27460143]
[-0.01236105  0.15959139 -0.11603987 -0.60000406]
[-0.00916922 -0.03373232 -0.12803995 -0.34600788]
[-0.00984387  0.16295634 -0.13496011 -0.67616672]
[-0.00658474 -0.03005784 -0.14848344 -0.42883609]
[-0.0071859  -0.22279937 -0.15706016 -0.18639892]
[-0.01164188 -0.41536628 -0.16078814  0.05291002]
[-0.01994921 -0.21834786 -0.15972994 -0.28587401]
[-0.02431617 -0.41087413 -0.16544742 -0.04752199]
[-0.03253365 -0.21381395 -0.16639786 -0.38749584]
[-0.03680993 -0.40623133 -0.17414778 -0.15155186]
[-0.04493455 -0.20909897 -0.17717882 -0.49371888]
[-0.04911653 -0.40133771 -0.18705319 -0.26169352]


[ 0.09963517  1.18386852 -0.13341795 -1.84262415]
[ 0.12331254  1.38018644 -0.17027043 -2.17359263]
Episode finished after 10 timesteps
[ 0.0173378  -0.04737284  0.04719659  0.01625367]
[ 0.01639034  0.14704159  0.04752166 -0.2611726 ]
[ 0.01933117 -0.04872538  0.04229821  0.04611245]
[ 0.01835667 -0.24442753  0.04322046  0.35183508]
[ 0.01346812 -0.4401366   0.05025716  0.6578274 ]
[ 0.00466538 -0.63592074  0.06341371  0.96590219]
[-0.00805303 -0.44170519  0.08273175  0.69379555]
[-0.01688714 -0.2478224   0.09660766  0.42826147]
[-0.02184358 -0.44417031  0.10517289  0.74976851]
[-0.03072699 -0.25064407  0.12016826  0.49194703]
[-0.03573987 -0.44723784  0.1300072   0.81995557]
[-0.04468463 -0.64387649  0.14640631  1.15053892]
[-0.05756216 -0.45093639  0.16941709  0.90711481]
[-0.06658089 -0.64789675  0.18755939  1.24789628]
Episode finished after 14 timesteps
[ 0.01354681 -0.02408876  0.03812602  0.01015131]
[ 0.01306504 -0.21973616  0.03832905  0.31461548]
[ 0.00867031 -0.02518057  0.