In [3]:
import torch

# import numpy as np

In [4]:
torch.Tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])

PyTorch offers automatic differentiation and optimization.

We can define model in numpy like syntax.

In [9]:
x = torch.Tensor([2, 4]) # input
y_known = torch.Tensor([0, 1])
m = torch.randn(2, requires_grad=True) # param 1
b = torch.randn(1, requires_grad=True) # param 1

y = m*x + b # eq. of a line
loss = (torch.sum(y_known - y))**2
loss.backward()
m.grad

tensor([-17.4700, -34.9399])

Build network with nn module.

In [50]:
# x = np.random.randint(10, size=(5, 10))
# y = np.random.randint(2, size=(5, 4))
x = torch.randn((5, 10))
y = torch.randn((5, 4))
x, y
# torch.randn?

(tensor([[-2.9166,  0.0622, -0.3010,  0.0139, -0.3659, -1.3406, -1.4692,  1.1442,
          -1.2650, -0.1862],
         [-0.8419,  0.3537, -1.6760, -1.0152, -0.2306, -1.0599,  1.5273, -0.3614,
           1.2470, -0.3127],
         [-1.4074, -1.0965,  1.9976,  2.3740,  2.1991, -0.6624,  0.5846,  0.2733,
          -0.5533,  0.9958],
         [ 0.8398, -0.0386, -0.5947,  0.1982, -0.5249,  0.7767, -0.5157, -1.6524,
           2.8597,  1.4638],
         [ 0.9902, -1.3596,  0.9128, -0.1147,  1.5685, -0.0215, -1.0587, -0.7561,
           1.3370,  2.2807]]),
 tensor([[ 0.2235, -0.3106,  0.3313, -0.6066],
         [-0.3822, -1.4078,  0.4420,  0.1888],
         [ 1.0787, -0.6329, -0.2615, -0.1426],
         [-0.5385, -0.8825, -0.2440,  0.4959],
         [ 2.4771, -0.2515, -1.0360, -0.1410]]))

In [39]:
model = torch.nn.Sequential(
    torch.nn.Linear(10, 150),
    torch.nn.ReLU(),
    torch.nn.Linear(150, 4),
    torch.nn.ReLU()
)

loss_func = torch.nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [40]:
model

Sequential(
  (0): Linear(in_features=10, out_features=150, bias=True)
  (1): ReLU()
  (2): Linear(in_features=150, out_features=4, bias=True)
  (3): ReLU()
)

In [51]:
for step in range(100):
    y_pred = model(x)
    loss = loss_func(y_pred, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

To build more comlex models we do.

In [60]:
from torch.nn import Module, Linear

In [71]:
class MyNet(Module):
    
    def __init__(self):
        super(MyNet, self).__init__()
        self.fc1 = Linear(10, 150)
        self.fc2 = Linear(150, 4)
        
    def forward(self, x):
        x = torch.nn.ReLU()(self.fc1(x))
        x = torch.nn.ReLU()(self.fc2(x))
        return x

In [72]:
my_net = MyNet()
my_net.forward(x)

tensor([[0.1260, 0.0000, 0.2643, 0.4676],
        [0.4543, 0.0000, 0.4043, 0.3081],
        [0.0000, 0.0000, 0.4794, 0.3867],
        [0.0930, 0.0000, 0.0000, 0.4722],
        [0.0000, 0.0000, 0.0000, 0.2921]], grad_fn=<ReluBackward0>)